### ISSUE TITLE
Trouble Importing Reddit "Saved" Feed

### ISSUE THREAD

**Issue by Nezteb** [Ranchero-Software/NetNewsWireHelp#17]
If you go to https://ssl.reddit.com/prefs/feeds/ you'll see these feeds:
<img width="780" alt="Screen Shot 2022-01-23 at 12 00 25 PM" src="https://user-images.githubusercontent.com/3588798/150691590-9e35352f-1f8c-4a1c-82df-569aa3418eab.png">

I'm trying to use the "your saved links" one, which looks like: `https://www.reddit.com/user/Nezteb/saved.rss?feed=<token>&user=Nezteb`

When I try to import it into NNW, I get this error:
<img width="284" alt="Screen Shot 2022-01-23 at 12 03 21 PM" src="https://user-images.githubusercontent.com/3588798/150691702-299f0b7d-a1f7-461a-98a5-abb6dd317ecf.png">

If I open the same feed URL in a browser, it displays correctly and is valid XML.

Any ideas?

**Comment by vincode-io** [comment]
Do you have the Reddit Extension enabled?

**Comment by Nezteb** [comment]
I do.

I just disabled it, and now the Reddit "your saved links" feed imports correctly! Although I'm not sure what will happen if I re-enable it; I worry that refreshing the feed will cause the "Feed not found" error again. 🤔

I don't know if that is considered a "bug"?

**Comment by vincode-io** [comment]
This is an outstanding issue. You can't mix the Reddit Extension with the existing Reddit Web Feeds. We have a bug ticket for it on NetNewsWire Issues. If you reenable the Reddit Extension the added Reddit Web Feeds won't update. Sorry.

BTW, this Issue tracker is for the help book. Since this issue has a ticket in the correct GitHub project, I'm going to close it.
